/**
 * Constants and configuration defaults for the IndexNow CLI tool.
 *
 * @module constants
 */

/** IndexNow API endpoint for URL submission. */
export const INDEXNOW_API_URL = 'https://api.indexnow.org/indexnow';

/** Number of URLs to submit per API request. */
export const CHUNK_SIZE = 100;

/** Default sitemap filename (generated by next-sitemap). */
export const DEFAULT_SITEMAP_FILE = 'sitemap-0.xml';

/** Sitemap output directory (relative to project root or configured outDir). */
export const DEFAULT_SITEMAP_DIR = 'public';

/** IndexNow key verification filename extension. */
export const KEY_FILE_EXTENSION = '.txt';

/** Default IndexNow API key — used when neither --key option nor INDEXNOW_KEY env var is provided. */
export const DEFAULT_INDEXNOW_KEY = '91c80f732f4e4e5b80b4c02a7e8c9e9c';

/** Conventional Next.js config filenames to detect a Next.js project. */
export const NEXT_CONFIG_FILES = ['next.config.ts', 'next.config.mjs', 'next.config.cjs', 'next.config.js'];

/** Conventional next-sitemap config filenames. */
export const NEXT_SITEMAP_CONFIG_FILES = [
  'next-sitemap.config.ts',
  'next-sitemap.config.mjs',
  'next-sitemap.config.cjs',
  'next-sitemap.config.js',
];

/** Directories that indicate a Next.js build has been run. */
export const NEXT_BUILD_DIRS = ['.next'];
